### ISSUE TITLE
Question: How are 64-bit integers supported on 32-bit platforms?

### ISSUE THREAD

**Issue by AKushWarrior** [dart-lang/fixnum#58]
Obviously, when compiled to JS, there is no native ability to store and manipulate 64 bit integers. The README notes that integer implementations work the same across JS and VM. I don't really have the time to deep dive into the code to see how this works, so I was wondering if you guys could summarize for me.

**Comment by rakudrama** [comment]
[This comment ](https://github.com/dart-lang/fixnum/blob/master/lib/src/int64.dart#L15) in the `Int64` class explains how an `Int64` spreads the 64 bits across several `int` fields, each containing smaller values that no problem for any platform.

**Comment by AKushWarrior** [comment]
Thanks for the link! My curiosity is satisfied, and the solution seems pretty neat.
